spring:
  application:
    name: Customer Support Ticketing System

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300
    refreshTokenExpiration: 604800

  web:
    resources:
      add-mappings: false

server:
  error:
    whitelabel:
      enabled: false
    path: /error
    include-message: always
    include-exception: true
